function outpict = imgenerate(s,varargin)
%   IMGENERATE(SIZE, {OPTIONS})
%       Generate simple images interactively via a graphical interface
%
%   SIZE is a two-element vector specifying image dimensions
%
%   Optional arguments are:
%   'invert' inverts the display of colors and images
%       This is used if using an inverted display
%   'imcomposemode' is not used in standalone operation
%
%   Default output class is double
%   Default image type is RGB
%       
%   Tested on R2009b and R2015b (in Linux).  If it doesn't work in a different environment
%   don't be too terribly surprised.  It's still a little half-baked at the moment anyway.
%
%   See also: IMCOMPOSE, IMMODIFY, COLORPICT, LINGRAD, RADGRAD, RANDLINES, RANDSPOTS, PERLIN.

% TO DO:
% add more modes or consider a means to generate masks from a layer
% palette control buttons should make more sense
% there really is no 'fg' or 'bg'


for a = 1:1:length(varargin);
    if ischar(varargin{a})
		switch lower(varargin{a})
			case 'imcomposemode'
				imcomposemode = 1;
			case 'invert'
				invert = 1;
		end
    end
end

if ~exist('imcomposemode','var')
	imcomposemode = 0;
end

if ~exist('invert','var')
	invert = 0;
end

% implement singleton behavior
h = findall(0,'tag','IMGENERATE_GUI');
if ~isempty(h)
	% raise window if already open
	figure(h);
else
	% ui data initialization
	methodstrings = {'solid color','checkerboard','grid','linear gradient','radial gradient', ...
		'random lines','random shapes','clouds'};
	thismode = 1;
	autopreview = 1;
	protoimage = [];
	s = s(1:2);

	% parameters
	fgc = [0 0 0];
	bgc = [1 1 1];
	width = [10 1];
	height = width;
	startpos = [0 0];
	endpos = [1 1];
	radius = 1;
	easemodestrings = {'invert','softinvert','linear','softease','cosine','ease'};
	thiseasemode = 3;
	colorenabled = 1;
	thisdim = 1;
	randmodestrings = {'normal','walks','ramps'};
	thisrandmode = 1;
	sparsity = 0.75;
	rate = 1;
	contrastenhanced = 1;
	numspots = 25;
	spotmodestrings = {'circle','rectangle','square'};
	thisspotmode = 1;
	spotbounds = [10 50];
	opacity = [0.1 0.5];
	fill = [0.2 0.6];
	correl = 1;

	% prepare the figure elements
	handles = struct([]);
	figuresetup();
	panels = [handles.editorpanel1;
		handles.editorpanel2;
		handles.editorpanel3;
		handles.editorpanel4;
		handles.editorpanel5;
		handles.editorpanel6;
		handles.editorpanel7;
		handles.editorpanel8];

	if invert
		set(handles.fgcolorswatch,'foregroundcolor',1-fgc,'backgroundcolor',1-fgc);
		set(handles.bgcolorswatch,'foregroundcolor',1-bgc,'backgroundcolor',1-bgc);
	else
		set(handles.fgcolorswatch,'foregroundcolor',fgc,'backgroundcolor',fgc);
		set(handles.bgcolorswatch,'foregroundcolor',bgc,'backgroundcolor',bgc);
	end
	
	if ~imcomposemode
		set(handles.IMGENERATE_GUI,'closerequestfcn',@commitbutton_CBF)
	end
	
	if autopreview
		incrementpreview();
	end
end


function figuresetup()
	pw = 220;
	fhm = 0.015;
	
	% FIGURE AND TAB PANES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	h1 = figure(...
	'Units','normalized',...
	'MenuBar','none',...
	'Name','imgenerate_gui',...
	'NumberTitle','off',...
	'outerPosition',[0.125 0.125 0.75 0.75],...
	'HandleVisibility','callback',...
	'Tag','IMGENERATE_GUI');

	pph = getpixelposition(h1);
	pw = pw/pph(3);

	% AXES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	axes(...
	'Parent',h1,...
	'Position',[fhm 0.0299043062200957 1-2.5*fhm-pw 0.873205741626794],...
	'CameraPosition',[0.5 0.5 9.16025403784439],...
	'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
	'Color',get(0,'defaultaxesColor'),...
	'ColorOrder',get(0,'defaultaxesColorOrder'),...
	'LooseInset',[0.154399205561073 0.117262905162065 0.112830188679245 0.0799519807923169],...
	'XColor',get(0,'defaultaxesXColor'),...
	'XTick',0,...
	'XTickLabel',{  blanks(0) },...
	'XTickLabelMode','manual',...
	'XTickMode','manual',...
	'YColor',get(0,'defaultaxesYColor'),...
	'YTick',0,...
	'YTickLabel',{  blanks(0) },...
	'YTickLabelMode','manual',...
	'YTickMode','manual',...
	'ZColor',get(0,'defaultaxesZColor'),...
	'Tag','axes1',...
	'Visible','on');

	%% TOP PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	uicontrol(...
	'Parent',h1,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.514312096029548 0.929425837320574 0.111726685133887 0.0311004784688995],...
	'String','Preview Layer',...
	'TooltipString','Preview this layer before applying to composition',...
	'Tag','previewbutton',...
	'callback',@previewbutton_CBF);

	uicontrol(...
	'Parent',h1,...
	'Units','normalized',...
	'Position',[0.63 0.929425837320574 0.08 0.0311004784688995],...
	'String','Auto',...
	'value',autopreview,...
	'Style','checkbox',...
	'TooltipString','Automatically update layer preview',...
	'Tag','autopreviewcheckbox',...
	'callback',{@setparam,'autopreview'});

	uicontrol(...
	'Parent',h1,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.128347183748846 0.930622009569378 0.111726685133887 0.0287081339712919],...
	'String','Commit',...
	'TooltipString','<html>Add this layer to the composition and recompose.<br/>Clicking again will update the new layer.<br/>Close window or click ''Generate Layer'' to start another new layer<br/></html>',...
	'Tag','commitbutton',...
	'callback',@commitbutton_CBF);

	uicontrol(...
	'Parent',h1,...
	'Units','normalized',...
	'Position',[0.754385964912281 0.927033492822966 0.204062788550323 0.0358851674641148],...
	'String',methodstrings,...
	'Style','popupmenu',...
	'Value',1,...
	'Tag','modemenu',...
	'callback',@modemenu_CBF);

	%% COLORPICT PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	lpos = [0.10 0 0.5 0.03];
	tbpos = [0.60 0 0.3 0.042];
	
	ep1 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel1',...
	'Clipping','on',...
	'visible','on',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	uicontrol(...
	'Parent',ep1,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.939521800281294 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select layer color',...
	'Tag','fgcolorbutton',...
	'callback',{@setfgbg,'fg'});

	uicontrol(...
	'Parent',ep1,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.939521800281294 0.38 0.04],...
	'foregroundcolor',[0 0 0],...
	'backgroundcolor',[0 0 0],...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','fgcolorswatch');

	% direct entry
	uicontrol(...
	'Parent',ep1,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',[0.1 0.939-0.005-0.06 0.8 0.042],...
	'String',mat2str(fgc,4),...
	'Style','edit',...
	'TooltipString','Select layer color',...
	'Tag','cptuplebox',...
	'callback',{@setfgbg,'fgdirect'});
	
	%% CHECKERBOARD PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep2 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel2',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	% fg color widget
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.939521800281294 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select FG color',...
	'Tag','fgcolorbutton',...
	'callback',{@setfgbg,'fg'});
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.939521800281294 0.38 0.04],...
	'foregroundcolor',fgc,...
	'backgroundcolor',fgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','fgcolorswatch');

	% bg color widget
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.883 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select BG color',...
	'Tag','bgcolorbutton',...
	'callback',{@setfgbg,'bg'});
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.883 0.38 0.04],...
	'foregroundcolor',bgc,...
	'backgroundcolor',bgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','bgcolorswatch');

	% palette controls
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05 0.883-0.06 0.3 0.04],...
	'String','FG <> BG',...
	'TooltipString','Swap FG & BG colors',...
	'Tag','swapfgbgbutton',...
	'callback',{@palettecontrol,'swap'});
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.3 0.883-0.06 0.3 0.04],...
	'String','FG >> BG',...
	'TooltipString','Copy FG color to BG color',...
	'Tag','fg2bgbutton',...
	'callback',{@palettecontrol,'fg2bg'});
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.6 0.883-0.06 0.3 0.04],...
	'String','FG << BG',...
	'TooltipString','Copy BG color to FG color',...
	'Tag','bg2fgbutton',...
	'callback',{@palettecontrol,'bg2fg'});

	% blockwidth
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.81293952180-0.06 0 0],...
	'String',width(1),...
	'Style','edit',...
	'TooltipString','horizontal blocksize',...
	'Tag','xsize',...
	'callback',{@setparam,'width',1});
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.81715893108-0.06 0 0],...
	'String','Block Width',...
	'Style','text',...
	'Tag','widthlabel');

	% blockheight
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.7566807313-0.06 0 0],...
	'String',height(1),...
	'Style','edit',...
	'TooltipString','vertical blocksize',...
	'Tag','ysize',...
	'callback',{@setparam,'height',1});
	uicontrol(...
	'Parent',ep2,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.7609001406-0.06 0 0],...
	'String','Block Height',...
	'Style','text',...
	'Tag','heightlabel');

	%% GRID PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep3 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel3',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	% fg color widget
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.939521800281294 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select FG color',...
	'Tag','fgcolorbutton',...
	'callback',{@setfgbg,'fg'});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.939521800281294 0.38 0.04],...
	'foregroundcolor',fgc,...
	'backgroundcolor',fgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','fgcolorswatch');

	% bg color widget
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.883 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select BG color',...
	'Tag','bgcolorbutton',...
	'callback',{@setfgbg,'bg'});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.883 0.38 0.04],...
	'foregroundcolor',bgc,...
	'backgroundcolor',bgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','bgcolorswatch');

	% palette controls
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05 0.883-0.06 0.3 0.04],...
	'String','FG <> BG',...
	'TooltipString','Swap FG & BG colors',...
	'Tag','swapfgbgbutton',...
	'callback',{@palettecontrol,'swap'});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.3 0.883-0.06 0.3 0.04],...
	'String','FG >> BG',...
	'TooltipString','Copy FG color to BG color',...
	'Tag','fg2bgbutton',...
	'callback',{@palettecontrol,'fg2bg'});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.6 0.883-0.06 0.3 0.04],...
	'String','FG << BG',...
	'TooltipString','Copy BG color to FG color',...
	'Tag','bg2fgbutton',...
	'callback',{@palettecontrol,'bg2fg'});

	% blockwidth
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.8129395218-0.06 0 0],...
	'String',width(1),...
	'Style','edit',...
	'TooltipString','horizontal blocksize',...
	'Tag','xsize',...
	'callback',{@setparam,'width',1});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.8171589310-0.06 0 0],...
	'String','Block Width',...
	'Style','text',...
	'Tag','widthlabel');

	% blockheight
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.7566807313-0.06 0 0],...
	'String',height(1),...
	'Style','edit',...
	'TooltipString','vertical blocksize',...
	'Tag','ysize',...
	'callback',{@setparam,'height',1});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.7609001406-0.06 0 0],...
	'String','Block Height',...
	'Style','text',...
	'Tag','heightlabel');

	% blocklinewidth
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.812939521800281-0.12-0.06 0 0],...
	'String',width(2),...
	'Style','edit',...
	'TooltipString','width of vertical lines',...
	'Tag','xlw',...
	'callback',{@setparam,'width',2});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.817158931082982-0.12-0.06 0 0],...
	'String','Line Width X',...
	'Style','text',...
	'Tag','linexlabel');

	% blocklineheight
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.756680731364276-0.12-0.06 0 0],...
	'String',height(2),...
	'Style','edit',...
	'TooltipString','width of horizontal lines',...
	'Tag','ylw',...
	'callback',{@setparam,'height',2});
	uicontrol(...
	'Parent',ep3,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.760900140646976-0.12-0.06 0 0],...
	'String','Line Width Y',...
	'Style','text',...
	'Tag','lineylabel');

	%% LINGRAD PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep4 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel4',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	% fg color widget
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.939521800281294 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select start color',...
	'Tag','fgcolorbutton',...
	'callback',{@setfgbg,'fg'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.939521800281294 0.38 0.04],...
	'foregroundcolor',fgc,...
	'backgroundcolor',fgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','fgcolorswatch');

	% bg color widget
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.883 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select end color',...
	'Tag','bgcolorbutton',...
	'callback',{@setfgbg,'bg'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.883 0.38 0.04],...
	'foregroundcolor',bgc,...
	'backgroundcolor',bgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','bgcolorswatch');

	% palette controls
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05 0.883-0.06 0.3 0.04],...
	'String','FG <> BG',...
	'TooltipString','Swap FG & BG colors',...
	'Tag','swapfgbgbutton',...
	'callback',{@palettecontrol,'swap'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.3 0.883-0.06 0.3 0.04],...
	'String','FG >> BG',...
	'TooltipString','Copy FG color to BG color',...
	'Tag','fg2bgbutton',...
	'callback',{@palettecontrol,'fg2bg'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.6 0.883-0.06 0.3 0.04],...
	'String','FG << BG',...
	'TooltipString','Copy BG color to FG color',...
	'Tag','bg2fgbutton',...
	'callback',{@palettecontrol,'bg2fg'});

	% start position
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.05 0.812939521800281-0.06 0.42 0.042],...
	'String','Start Position',...
	'TooltipString','Select start position with mouse',...
	'Tag','startposbutton',...
	'callback',{@selectpoint,'start'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',[0.521400778210117 0.812939521800281-0.06 0.42 0.0421940928270042],...
	'String',sprintf('[%0.3g %0.3g]',startpos(1),startpos(2)),...
	'Style','edit',...
	'TooltipString','start position [x y], normalized to image size',...
	'Tag','startposbox',...
	'callback',{@setparam,'startpos'});

	% end position
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.05 0.756680731364276-0.06 0.42 0.042],...
	'String','End Position',...
	'TooltipString','Select end position with mouse',...
	'Tag','endposbutton',...
	'callback',{@selectpoint,'end'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',[0.517509727626459 0.756680731364276-0.06 0.42 0.0421940928270042],...
	'String',sprintf('[%0.3g %0.3g]',endpos(1),endpos(2)),...
	'Style','edit',...
	'TooltipString','end position [x y], normalized to image size',...
	'Tag','endposbox',...
	'callback',{@setparam,'endpos'});
	
	% ease mode
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'Position',[0.10 0.812939521800281-0.16-0.06 0.8 0.0421940928270042],...
	'String',easemodestrings,...
	'Style','popupmenu',...
	'Value',thiseasemode,...
	'Tag','easemodemenu',...
	'callback',{@setparam,'easemode'});
	uicontrol(...
	'Parent',ep4,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',[0.11284046692607 0.817158931082982-0.12-0.06 0.88 0.029535864978903],...
	'String','Interpolation Method',...
	'Style','text',...
	'Tag','easemodelabel');

	%% RADGRAD PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep5 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel5',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	% fg color widget
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.939521800281294 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select start color',...
	'Tag','fgcolorbutton',...
	'callback',{@setfgbg,'fg'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.939521800281294 0.38 0.04],...
	'foregroundcolor',fgc,...
	'backgroundcolor',fgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','fgcolorswatch');

	% bg color widget
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.501945525291829 0.883 0.392996108949416 0.0421940928270042],...
	'String','Select',...
	'TooltipString','Select end color',...
	'Tag','bgcolorbutton',...
	'callback',{@setfgbg,'bg'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',12,...
	'fontweight','bold',...
	'HorizontalAlignment','center',...
	'Position',[0.108949416342412 0.883 0.38 0.04],...
	'foregroundcolor',bgc,...
	'backgroundcolor',bgc,...
	'String','██████',...
	'visible','on',...
	'Style','text',...
	'Tag','bgcolorswatch');

	% palette controls
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05 0.883-0.06 0.3 0.04],...
	'String','FG <> BG',...
	'TooltipString','Swap FG & BG colors',...
	'Tag','swapfgbgbutton',...
	'callback',{@palettecontrol,'swap'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.3 0.883-0.06 0.3 0.04],...
	'String','FG >> BG',...
	'TooltipString','Copy FG color to BG color',...
	'Tag','fg2bgbutton',...
	'callback',{@palettecontrol,'fg2bg'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',8,...
	'Position',[0.05+0.6 0.883-0.06 0.3 0.04],...
	'String','FG << BG',...
	'TooltipString','Copy BG color to FG color',...
	'Tag','bg2fgbutton',...
	'callback',{@palettecontrol,'bg2fg'});

	% start position
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.05 0.812939521800281-0.06 0.42 0.042],...
	'String','Start Position',...
	'TooltipString','Select start position with mouse',...
	'Tag','startposbutton',...
	'callback',{@selectpoint,'start'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',[0.521400778210117 0.812939521800281-0.06 0.42 0.0421940928270042],...
	'String',sprintf('[%0.3g %0.3g]',startpos(1),startpos(2)),...
	'Style','edit',...
	'TooltipString','start position [x y], normalized to image size',...
	'Tag','startposbox',...
	'callback',{@setparam,'startpos'});

	% radius
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.05 0.756680731364276-0.06 0.42 0.042],...
	'String','Radius',...
	'TooltipString','Select end position with mouse',...
	'Tag','radiusbutton',...
	'callback',{@selectpoint,'radius'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',[0.517509727626459 0.756680731364276-0.06 0.42 0.0421940928270042],...
	'String',radius,...
	'Style','edit',...
	'TooltipString','radius, normalized to image diagonal',...
	'Tag','radposbox',...
	'callback',{@setparam,'radius'});
	
	% ease mode
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'Position',[0.10 0.812939521800281-0.16-0.06 0.8 0.0421940928270042],...
	'String',easemodestrings,...
	'Style','popupmenu',...
	'Value',thiseasemode,...
	'Tag','easemodemenu',...
	'callback',{@setparam,'easemode'});
	uicontrol(...
	'Parent',ep5,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',[0.11284046692607 0.817158931082982-0.12-0.06 0.88 0.029535864978903],...
	'String','Interpolation Method',...
	'Style','text',...
	'Tag','easemodelabel');

	%% RANDLINES PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep6 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel6',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'Position',[0.10 0.939-0.06 0.8 0.0421940928270042],...
	'String',{'vertical','horizontal'},...
	'Style','popupmenu',...
	'Value',thisdim,...
	'Tag','thisdimmenu',...
	'tooltipstring','orientation of lines',...
	'callback',{@setparam,'thisdim'});

	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'Position',[0.10 0.939 0.8 0.0421940928270042],...
	'String',randmodestrings,...
	'Style','popupmenu',...
	'Value',thisrandmode,...
	'Tag','thisrandmodemenu',...
	'callback',{@setparam,'thisrandmode'});

	% sparsity
	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.12 0 0],...
	'String',sparsity,...
	'Style','edit',...
	'TooltipString','threshold before displacement [0 1]',...
	'Tag','sparsitybox',...
	'callback',{@setparam,'sparsity'});
	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.12 0 0],...
	'String','Sparsity',...
	'Style','text',...
	'Tag','sparsitylabel');

	% rate
	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.18 0 0],...
	'String',rate,...
	'Style','edit',...
	'TooltipString','rate at which walk or ramp progresses (normalized)',...
	'Tag','ratebox',...
	'enable','off',...
	'callback',{@setparam,'rate'});
	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.18 0 0],...
	'String','Rate',...
	'Style','text',...
	'Tag','ratelabel');

	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.11284046692607 0.939-0.24 0.88 0.029535864978903],...
	'String','Color Mode',...
	'Style','checkbox',...
	'value',colorenabled,...
	'TooltipString','control RGB channel independence',...
	'Tag','colorenabledcheckbox',...
	'callback',{@setparam,'colorenabled'});

	uicontrol(...
	'Parent',ep6,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.11284046692607 0.939-0.30 0.88 0.029535864978903],...
	'String','Enhance Contrast',...
	'Style','checkbox',...
	'value',contrastenhanced,...
	'TooltipString','helpful for walks of high sparsity',...
	'Tag','contrastcheckbox',...
	'callback',{@setparam,'contrastenhanced'});

	%% RANDSPOTS PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep7 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel7',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'Position',[0.10 0.939 0.8 0.0421940928270042],...
	'String',spotmodestrings,...
	'Style','popupmenu',...
	'Value',thisspotmode,...
	'Tag','spotmodemenu',...
	'tooltipstring','type of shape',...
	'callback',{@setparam,'thisspotmode'});

	% numspots
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.06 0 0],...
	'String',numspots,...
	'Style','edit',...
	'TooltipString','number of shapes to draw',...
	'Tag','numspotsbox',...
	'callback',{@setparam,'numspots'});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.06 0 0],...
	'String','Spot Count',...
	'Style','text',...
	'Tag','numspotslabel');

	% spotbounds min
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.12 0 0],...
	'String',spotbounds(1),...
	'Style','edit',...
	'TooltipString','minimum spot size (px)',...
	'Tag','spotboundminsbox',...
	'callback',{@setparam,'spotbounds',(1)});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.12 0 0],...
	'String','Min Size',...
	'Style','text',...
	'Tag','spotboundminlabel');

	% spotbounds max
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.18 0 0],...
	'String',spotbounds(2),...
	'Style','edit',...
	'TooltipString','maximum spot size (px)',...
	'Tag','spotboundmaxsbox',...
	'callback',{@setparam,'spotbounds',(2)});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.18 0 0],...
	'String','Max Size',...
	'Style','text',...
	'Tag','spotboundmaxlabel');

	% opacity min
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.24 0 0],...
	'String',opacity(1),...
	'Style','edit',...
	'TooltipString','minimum spot opacity',...
	'Tag','opacityminsbox',...
	'callback',{@setparam,'opacity',(1)});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.24 0 0],...
	'String','Min Opacity',...
	'Style','text',...
	'Tag','opacityminlabel');

	% opacity max
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.30 0 0],...
	'String',opacity(2),...
	'Style','edit',...
	'TooltipString','maximum spot opacity',...
	'Tag','opacitymaxsbox',...
	'callback',{@setparam,'opacity',(2)});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.30 0 0],...
	'String','Max Opacity',...
	'Style','text',...
	'Tag','opacitymaxlabel');

	% fill min
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.36 0 0],...
	'String',fill(1),...
	'Style','edit',...
	'TooltipString','minimum spot fill',...
	'Tag','fillminsbox',...
	'callback',{@setparam,'fill',(1)});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.36 0 0],...
	'String','Min Fill',...
	'Style','text',...
	'Tag','fillminlabel');

	% fill max
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.42 0 0],...
	'String',fill(2),...
	'Style','edit',...
	'TooltipString','maximum spot fill',...
	'Tag','fillmaxsbox',...
	'callback',{@setparam,'fill',(2)});
	uicontrol(...
	'Parent',ep7,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.42 0 0],...
	'String','Max Fill',...
	'Style','text',...
	'Tag','fillmaxlabel');

	%% PERLIN PANEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	ep8 = uipanel(...
	'Parent',h1,...
	'Title','Edit Parameters',...
	'Tag','editorpanel8',...
	'Clipping','on',...
	'visible','off',...
	'Position',[1-fhm-pw 0.0311004784688995 pw 0.87200956937799]);

	uicontrol(...
	'Parent',ep8,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.11284046692607 0.939 0.88 0.029535864978903],...
	'String','Color Mode',...
	'Style','checkbox',...
	'value',colorenabled,...
	'TooltipString','control RGB channel independence',...
	'Tag','colorenabledcheckbox',...
	'callback',{@setparam,'colorenabled'});
	
	uicontrol(...
	'Parent',ep8,...
	'Units','normalized',...
	'FontSize',10,...
	'Position',[0.11284046692607 0.939-0.06 0.88 0.029535864978903],...
	'String','Enhance Contrast',...
	'Style','checkbox',...
	'value',contrastenhanced,...
	'TooltipString','increase contrast',...
	'Tag','contrastcheckbox',...
	'callback',{@setparam,'contrastenhanced'});

	% correlation
	uicontrol(...
	'Parent',ep8,...
	'Units','normalized',...
	'BackgroundColor',[1 1 1],...
	'HorizontalAlignment','left',...
	'Position',tbpos+[0 0.939-0.005-0.12 0 0],...
	'String',correl,...
	'Style','edit',...
	'TooltipString','channel correlation scaling factor',...
	'Tag','correlbox',...
	'callback',{@setparam,'correl'});
	uicontrol(...
	'Parent',ep8,...
	'Units','normalized',...
	'FontSize',10,...
	'HorizontalAlignment','left',...
	'Position',lpos+[0 0.939-0.12 0 0],...
	'String','Correlation',...
	'Style','text',...
	'Tag','correllabel');



	% all child object handles in figure 
	handles = guihandles(h1);
end

function modemenu_CBF(objh,~)
	thismode = get(objh,'value');
	for m = 1:length(panels)
		if m ~= thismode
			set(panels(m),'visible','off')
		else
			set(panels(m),'visible','on')
		end
	end
	incrementpreview();
end

% select fg or bg color using picker and swatch in panel
function setfgbg(objh,~,whichcolor)
	switch whichcolor
		case 'fg'
			if invert
				fgc = cpicktool(fgc,'invert');
			else
				fgc = cpicktool(fgc);
			end
		case 'bg'
			if invert
				bgc = cpicktool(bgc,'invert');
			else
				bgc = cpicktool(bgc);
			end
		case 'fgdirect'
			fgc = str2num(get(objh,'string'));
		case 'bgdirect'
			bgc = str2num(get(objh,'string'));
	end
	updateswatches(whichcolor);
	incrementpreview();
end

function updateswatches(whichswatch)
	switch whichswatch
		case {'fg','fgdirect'}
			if invert
				set(handles.fgcolorswatch,'foregroundcolor',1-fgc,'backgroundcolor',1-fgc);
			else
				set(handles.fgcolorswatch,'foregroundcolor',fgc,'backgroundcolor',fgc);
			end
			set(handles.cptuplebox,'string',mat2str(fgc,4))
		case {'bg','bgdirect'}
			if invert
				set(handles.bgcolorswatch,'foregroundcolor',1-bgc,'backgroundcolor',1-bgc);
			else
				set(handles.bgcolorswatch,'foregroundcolor',bgc,'backgroundcolor',bgc);
			end
	end
end

function palettecontrol(~,~,whichop)
	switch whichop
		case 'swap'
			t = fgc; fgc = bgc; bgc = t;
			updateswatches('bg');
			updateswatches('fg');
		case 'fg2bg'
			bgc = fgc;
			updateswatches('bg');
		case 'bg2fg'
			fgc = bgc;
			updateswatches('fg');
	end
	incrementpreview();
end

function selectpoint(~,~,whichpt)
	[sx sy] = ginput(1);
	point = [sx/s(2) sy/s(1)];
	switch whichpt
		case 'start'
			startpos = point;
			set(handles.startposbox,'string', ...
				sprintf('[%0.3g %0.3g]',startpos(1),startpos(2)));
		case 'end'
			endpos = point;
			set(handles.endposbox,'string', ...
				sprintf('[%0.3g %0.3g]',endpos(1),endpos(2)));
		case 'radius'
			radius = sqrt((point(1)-startpos(1))^2 + (point(2)-startpos(2))^2)/1.414;
			set(handles.radposbox,'string', ...
				sprintf('%0.3g',radius));
	end
	incrementpreview();
end

function setparam(objh,~,param,idx)
	switch param
		case 'width'
			width(idx) = str2double(get(objh,'string'));
		case 'height'
			height(idx) = str2double(get(objh,'string'));
		case 'startpos'
			startpos = str2num(get(objh,'string'));
		case 'endpos'
			endpos = str2num(get(objh,'string'));
		case 'radius'
			radius = str2double(get(objh,'string'));
		case 'easemode'
			thiseasemode = get(objh,'value');
		case 'thisdim'
			thisdim = get(objh,'value');
		case 'thisrandmode'
			thisrandmode = get(objh,'value');
			if thisrandmode == 1
				set(handles.ratebox,'enable','off')
			else
				set(handles.ratebox,'enable','on')
			end
		case 'colorenabled'
			colorenabled = get(objh,'value');
		case 'sparsity'
			sparsity = str2double(get(objh,'string'));
		case 'rate'
			rate = str2double(get(objh,'string'));	
		case 'contrastenhanced'
			contrastenhanced = get(objh,'value');
		case 'numspots'
			numspots = str2double(get(objh,'string'));
		case 'spotbounds'	
			spotbounds(idx) = str2double(get(objh,'string'));
		case 'opacity'	
			opacity(idx) = str2double(get(objh,'string'));	
		case 'fill'	
			fill(idx) = str2double(get(objh,'string'));
		case 'thisspotmode'
			thisspotmode = get(objh,'value');	
		case 'correl'
			correl = str2double(get(objh,'string'));
		case 'autopreview'
			autopreview = get(objh,'value');	
	end
	incrementpreview();
end

function incrementpreview(~,~)
	if autopreview
		previewbutton_CBF();
	end
end

function previewbutton_CBF(~,~)
	h = handles.axes1;
	if strcmpi(get(h,'type'),'image')
		h = get(h,'parent');
	end
	
	mode = methodstrings{thismode};
	switch mode
		case 'solid color'
			protoimage = colorpict(s,fgc,'double');
		case 'checkerboard' 
			[xx yy] = meshgrid(1:s(2),1:s(1));
			mask = xor(mod(xx-1,width(1)*2) < width(1),mod(yy-1,height(1)*2) < height(1));
			protoimage = colorpict(s,bgc,'double');
			protoimage = replacepixels(fgc,protoimage,mask);
		case 'grid' 
			[xx yy] = meshgrid(1:s(2),1:s(1));
			mask = or(mod(xx,width(1)) < width(2),mod(yy,height(1)) < height(2));
			protoimage = colorpict(s,bgc,'double');
			protoimage = replacepixels(fgc,protoimage,mask);
		case 'linear gradient'
			protoimage = lingrad([s 3],[fliplr(startpos);fliplr(endpos)], ...
				[fgc;bgc],easemodestrings{thiseasemode},'double');
		case 'radial gradient'
			protoimage = radgrad([s 3],fliplr(startpos),radius, ...
				[fgc;bgc],easemodestrings{thiseasemode},'double');

		case 'random lines'
			if colorenabled
				protoimage = randlines(s,thisdim,'sparsity',sparsity, ...
					'mode',randmodestrings{thisrandmode},'rate',rate,'outclass','double');
			else
				protoimage = repmat(randlines(s,thisdim,'sparsity',sparsity,'mono', ...
					'mode',randmodestrings{thisrandmode},'rate',rate,'outclass','double'),[1 1 3]);
			end
			if contrastenhanced
				protoimage = imlnc(protoimage);
			end
		case 'random shapes'
			protoimage = imcast(randspots([s 3],numspots,spotbounds,opacity, ...
				spotmodestrings{thisspotmode},fill),'double');
		case 'clouds'
			if contrastenhanced
				protoimage = imlnc(perlin([s 3],'correl',correl,'outclass','double'));
			else
				protoimage = perlin([s 3],'correl',correl,'outclass','double');
			end
			if ~colorenabled
				protoimage = repmat(mono(protoimage,'y'),[1 1 3]);
			end
	end
	
	if invert
		imagetoshow = 1-imcast(protoimage,'double');
	else
		imagetoshow = protoimage;
	end
	
	k = safeimshow(imagetoshow,h);
	
	% axes mode is 'replace' so that imshow-tight works correctly
	% this means we lose access to the parent by tag after the first 
	% image is placed and need to find it via the image object itself
	set(k,'tag','axes1')
end

function k = safeimshow(imtoshow,h)
	if hasipt()
		% IF IPT IS INSTALLED
		k = imshow(imtoshow,'border','tight','parent',h);
	else
		% IPT NOT INSTALLED
		if size(imtoshow,3) == 1
			imtoshow = repmat(imtoshow,[1 1 3]);
		end
		k = image(imtoshow,'parent',h);
		axis(h,'off','tight','image')
	end
end

function commitbutton_CBF(~,~)
	if isempty(protoimage)
			previewbutton_CBF();
	end
		
	if imcomposemode
		% i don't know a better way to do this 
		% so i'm just using a dummy uicontrol object's CBF
		h = findall(0,'tag','IMCOMPOSE_GUI');
		dh = findall(h,'tag','generatordummy');
		cb = get(dh,'callback');
		cb(dh,[],protoimage);
	else 
		outpict = protoimage;
		delete(handles.IMGENERATE_GUI);
	end
end

if ~imcomposemode
	waitfor(handles.IMGENERATE_GUI);
end

% end main function block
end



